# Usar una imagen base de Node.js
FROM node:20-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Instalar dependencias nativas necesarias para paquetes como bcrypt
RUN apk add --no-cache python3 make g++

# Copiar package.json y tsconfig.json
COPY package.json .
COPY tsconfig.json .

# Crear directorio de src para evitar error en postinstall
RUN mkdir -p src

# Copiar el código fuente
COPY src ./src

# Instalar dependencias ignorando scripts para evitar el error de build
RUN npm install --ignore-scripts && npm rebuild bcrypt --build-from-source

# Comando para ejecutar la aplicación en modo desarrollo
CMD ["npx", "nodemon", "--transpile-only", "src/index.ts"] 