-- CORRECCIÓN MASIVA DE PRODUCTOS MAL CLASIFICADOS
-- Total de updates: 720

BEGIN;

UPDATE valuation_items SET subcategory_id = 54, category_id = 6 WHERE id = 301;
UPDATE inventario SET id = 'MDEP001' WHERE id = 'JUGP005';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 304;
UPDATE inventario SET id = 'ABDP001' WHERE id = 'JUGP006';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 305;
UPDATE inventario SET id = 'ABDP002' WHERE id = 'JUGP007';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 306;
UPDATE inventario SET id = 'ABDP003' WHERE id = 'JUGP008';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 307;
UPDATE inventario SET id = 'ABDP004' WHERE id = 'JUGP009';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 308;
UPDATE inventario SET id = 'ABDP005' WHERE id = 'JUGP010';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 309;
UPDATE inventario SET id = 'ABDP006' WHERE id = 'JUGP011';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 310;
UPDATE inventario SET id = 'ABDP007' WHERE id = 'JUGP012';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 311;
UPDATE inventario SET id = 'ABDP008' WHERE id = 'JUGP013';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 312;
UPDATE inventario SET id = 'ABDP009' WHERE id = 'JUGP014';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 313;
UPDATE inventario SET id = 'ABDP010' WHERE id = 'JUGP015';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 314;
UPDATE inventario SET id = 'ABDP011' WHERE id = 'JUGP016';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 315;
UPDATE inventario SET id = 'ABDP012' WHERE id = 'JUGP017';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 316;
UPDATE inventario SET id = 'ABDP013' WHERE id = 'JUGP018';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 317;
UPDATE inventario SET id = 'ABDP014' WHERE id = 'JUGP019';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 318;
UPDATE inventario SET id = 'ABDP015' WHERE id = 'JUGP020';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 319;
UPDATE inventario SET id = 'ABDP016' WHERE id = 'JUGP021';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 320;
UPDATE inventario SET id = 'ABDP017' WHERE id = 'JUGP022';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 321;
UPDATE inventario SET id = 'ABDP018' WHERE id = 'JUGP023';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 322;
UPDATE inventario SET id = 'ABDP019' WHERE id = 'JUGP024';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 323;
UPDATE inventario SET id = 'ABDP020' WHERE id = 'JUGP025';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 324;
UPDATE inventario SET id = 'ABDP021' WHERE id = 'JUGP026';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 325;
UPDATE inventario SET id = 'ABDP022' WHERE id = 'JUGP027';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 326;
UPDATE inventario SET id = 'ABDP023' WHERE id = 'JUGP028';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 327;
UPDATE inventario SET id = 'ABDP024' WHERE id = 'JUGP029';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 328;
UPDATE inventario SET id = 'ABDP025' WHERE id = 'JUGP030';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 329;
UPDATE inventario SET id = 'ABDP026' WHERE id = 'JUGP031';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 336;
UPDATE inventario SET id = 'EDLP001' WHERE id = 'JUGP032';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 337;
UPDATE inventario SET id = 'EDLP002' WHERE id = 'JUGP033';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 338;
UPDATE inventario SET id = 'EDLP003' WHERE id = 'JUGP034';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 339;
UPDATE inventario SET id = 'EDLP004' WHERE id = 'JUGP035';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 340;
UPDATE inventario SET id = 'EDLP005' WHERE id = 'JUGP036';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 342;
UPDATE inventario SET id = 'EDLP006' WHERE id = 'JUGP037';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 343;
UPDATE inventario SET id = 'EDLP007' WHERE id = 'JUGP038';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 344;
UPDATE inventario SET id = 'EDLP008' WHERE id = 'JUGP039';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 345;
UPDATE inventario SET id = 'EDLP009' WHERE id = 'JUGP040';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 346;
UPDATE inventario SET id = 'EDLP010' WHERE id = 'JUGP041';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 347;
UPDATE inventario SET id = 'EDLP011' WHERE id = 'JUGP042';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 348;
UPDATE inventario SET id = 'EDLP012' WHERE id = 'JUGP043';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 349;
UPDATE inventario SET id = 'EDLP013' WHERE id = 'JUGP044';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 350;
UPDATE inventario SET id = 'ABDP027' WHERE id = 'JUGP045';
UPDATE valuation_items SET subcategory_id = 49, category_id = 6 WHERE id = 351;
UPDATE inventario SET id = 'MDAP001' WHERE id = 'JUGP046';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 361;
UPDATE inventario SET id = 'ACRP001' WHERE id = 'JUGP051';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 366;
UPDATE inventario SET id = 'JDMP001' WHERE id = 'JUGP054';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 367;
UPDATE inventario SET id = 'JDMP002' WHERE id = 'JUGP055';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 368;
UPDATE inventario SET id = 'JDMP003' WHERE id = 'JUGP056';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 374;
UPDATE inventario SET id = 'DISP001' WHERE id = 'JUGP061';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 375;
UPDATE inventario SET id = 'JDMP004' WHERE id = 'JUGP062';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 376;
UPDATE inventario SET id = 'JDMP005' WHERE id = 'JUGP063';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 377;
UPDATE inventario SET id = 'ANDP002' WHERE id = 'JUGP064';
UPDATE valuation_items SET subcategory_id = 16, category_id = 2 WHERE id = 378;
UPDATE inventario SET id = 'MDCP001' WHERE id = 'JUGP065';
UPDATE valuation_items SET subcategory_id = 16, category_id = 2 WHERE id = 379;
UPDATE inventario SET id = 'MDCP002' WHERE id = 'JUGP066';
UPDATE valuation_items SET subcategory_id = 16, category_id = 2 WHERE id = 380;
UPDATE inventario SET id = 'MDCP003' WHERE id = 'JUGP067';
UPDATE valuation_items SET subcategory_id = 16, category_id = 2 WHERE id = 381;
UPDATE inventario SET id = 'MDCP004' WHERE id = 'JUGP068';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 382;
UPDATE inventario SET id = 'CAPP001' WHERE id = 'JUGP069';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 383;
UPDATE inventario SET id = 'CAPP002' WHERE id = 'JUGP070';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 384;
UPDATE inventario SET id = 'ACAP001' WHERE id = 'JUGP071';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 388;
UPDATE inventario SET id = 'ACRP002' WHERE id = 'JUGP075';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 393;
UPDATE inventario SET id = 'ACAP002' WHERE id = 'JUGP076';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 394;
UPDATE inventario SET id = 'DISP002' WHERE id = 'JUGP077';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 395;
UPDATE inventario SET id = 'DISP003' WHERE id = 'JUGP078';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 396;
UPDATE inventario SET id = 'DISP004' WHERE id = 'JUGP079';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 397;
UPDATE inventario SET id = 'DISP005' WHERE id = 'JUGP080';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 398;
UPDATE inventario SET id = 'DISP006' WHERE id = 'JUGP081';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 399;
UPDATE inventario SET id = 'DISP007' WHERE id = 'JUGP082';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 400;
UPDATE inventario SET id = 'DISP008' WHERE id = 'JUGP083';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 401;
UPDATE inventario SET id = 'DISP009' WHERE id = 'JUGP084';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 402;
UPDATE inventario SET id = 'DISP010' WHERE id = 'JUGP085';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 403;
UPDATE inventario SET id = 'DISP011' WHERE id = 'JUGP086';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 404;
UPDATE inventario SET id = 'DISP012' WHERE id = 'JUGP087';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 405;
UPDATE inventario SET id = 'DISP013' WHERE id = 'JUGP088';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 406;
UPDATE inventario SET id = 'DISP014' WHERE id = 'JUGP089';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 407;
UPDATE inventario SET id = 'DISP015' WHERE id = 'JUGP090';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 408;
UPDATE inventario SET id = 'DISP016' WHERE id = 'JUGP091';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 409;
UPDATE inventario SET id = 'DISP017' WHERE id = 'JUGP092';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 410;
UPDATE inventario SET id = 'DISP018' WHERE id = 'JUGP093';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 411;
UPDATE inventario SET id = 'DISP019' WHERE id = 'JUGP094';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 412;
UPDATE inventario SET id = 'DISP020' WHERE id = 'JUGP095';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 413;
UPDATE inventario SET id = 'ACAP003' WHERE id = 'JUGP096';
UPDATE valuation_items SET subcategory_id = 21, category_id = 3 WHERE id = 414;
UPDATE inventario SET id = 'MCBP002' WHERE id = 'JUGP097';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 415;
UPDATE inventario SET id = 'JDMP006' WHERE id = 'JUGP098';
UPDATE valuation_items SET subcategory_id = 50, category_id = 6 WHERE id = 416;
UPDATE inventario SET id = 'LYRP001' WHERE id = 'JUGP099';
UPDATE valuation_items SET subcategory_id = 17, category_id = 2 WHERE id = 422;
UPDATE inventario SET id = 'BPCP002' WHERE id = 'JUGP101';
UPDATE valuation_items SET subcategory_id = 54, category_id = 6 WHERE id = 427;
UPDATE inventario SET id = 'MDEP002' WHERE id = 'JUGP102';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 428;
UPDATE inventario SET id = 'ANDP003' WHERE id = 'JUGP103';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 429;
UPDATE inventario SET id = 'ANDP004' WHERE id = 'JUGP104';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 430;
UPDATE inventario SET id = 'TYBP004' WHERE id = 'JUGP105';
UPDATE valuation_items SET subcategory_id = 21, category_id = 3 WHERE id = 431;
UPDATE inventario SET id = 'MCBP003' WHERE id = 'JUGP106';
UPDATE valuation_items SET subcategory_id = 50, category_id = 6 WHERE id = 433;
UPDATE inventario SET id = 'LYRP002' WHERE id = 'JUGP108';
UPDATE valuation_items SET subcategory_id = 50, category_id = 6 WHERE id = 434;
UPDATE inventario SET id = 'LYRP003' WHERE id = 'JUGP109';
UPDATE valuation_items SET subcategory_id = 50, category_id = 6 WHERE id = 435;
UPDATE inventario SET id = 'LYRP004' WHERE id = 'JUGP110';
UPDATE valuation_items SET subcategory_id = 50, category_id = 6 WHERE id = 436;
UPDATE inventario SET id = 'LYRP005' WHERE id = 'JUGP111';
UPDATE valuation_items SET subcategory_id = 50, category_id = 6 WHERE id = 437;
UPDATE inventario SET id = 'LYRP006' WHERE id = 'JUGP112';
UPDATE valuation_items SET subcategory_id = 34, category_id = 4 WHERE id = 438;
UPDATE inventario SET id = 'PDAP001' WHERE id = 'JUGP113';
UPDATE valuation_items SET subcategory_id = 50, category_id = 6 WHERE id = 439;
UPDATE inventario SET id = 'LYRP007' WHERE id = 'JUGP114';
UPDATE valuation_items SET subcategory_id = 50, category_id = 6 WHERE id = 440;
UPDATE inventario SET id = 'LYRP008' WHERE id = 'JUGP115';
UPDATE valuation_items SET subcategory_id = 17, category_id = 2 WHERE id = 448;
UPDATE inventario SET id = 'BPCP003' WHERE id = 'JUGP122';
UPDATE valuation_items SET subcategory_id = 11, category_id = 2 WHERE id = 450;
UPDATE inventario SET id = 'CYMP001' WHERE id = 'JUGP123';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 453;
UPDATE inventario SET id = 'EDLP014' WHERE id = 'JUGP124';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 454;
UPDATE inventario SET id = 'EDLP015' WHERE id = 'JUGP125';
UPDATE valuation_items SET subcategory_id = 54, category_id = 6 WHERE id = 455;
UPDATE inventario SET id = 'MDEP003' WHERE id = 'JUGP126';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 456;
UPDATE inventario SET id = 'ACRP003' WHERE id = 'JUGP127';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 457;
UPDATE inventario SET id = 'ACRP004' WHERE id = 'JUGP128';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 458;
UPDATE inventario SET id = 'ACRP005' WHERE id = 'JUGP129';
UPDATE valuation_items SET subcategory_id = 28, category_id = 3 WHERE id = 459;
UPDATE inventario SET id = 'BANP001' WHERE id = 'JUGP130';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 460;
UPDATE inventario SET id = 'CAPP003' WHERE id = 'JUGP131';
UPDATE valuation_items SET subcategory_id = 16, category_id = 2 WHERE id = 463;
UPDATE inventario SET id = 'MDCP005' WHERE id = 'JUGP132';
UPDATE valuation_items SET subcategory_id = 16, category_id = 2 WHERE id = 464;
UPDATE inventario SET id = 'MDCP006' WHERE id = 'JUGP133';
UPDATE valuation_items SET subcategory_id = 54, category_id = 6 WHERE id = 466;
UPDATE inventario SET id = 'MDEP004' WHERE id = 'JUGP135';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 468;
UPDATE inventario SET id = 'ANDP005' WHERE id = 'JUGP136';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 471;
UPDATE inventario SET id = 'SORP001' WHERE id = 'JUGP137';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 474;
UPDATE inventario SET id = 'TYBP005' WHERE id = 'JUGP139';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 476;
UPDATE inventario SET id = 'ANDP006' WHERE id = 'JUGP141';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 477;
UPDATE inventario SET id = 'SORP002' WHERE id = 'JUGP142';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 478;
UPDATE inventario SET id = 'TYBP006' WHERE id = 'JUGP143';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 484;
UPDATE inventario SET id = 'ADAP001' WHERE id = 'JUGP145';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 485;
UPDATE inventario SET id = 'DISP021' WHERE id = 'JUGP146';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 488;
UPDATE inventario SET id = 'DISP022' WHERE id = 'JUGP148';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 490;
UPDATE inventario SET id = 'SORP003' WHERE id = 'JUGP149';
UPDATE valuation_items SET subcategory_id = 14, category_id = 2 WHERE id = 499;
UPDATE inventario SET id = 'COLP002' WHERE id = 'JUGP150';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 500;
UPDATE inventario SET id = 'CAPP004' WHERE id = 'JUGP151';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 502;
UPDATE inventario SET id = 'SORP004' WHERE id = 'JUGP153';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 504;
UPDATE inventario SET id = 'CAPP005' WHERE id = 'JUGP154';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 508;
UPDATE inventario SET id = 'TYBP007' WHERE id = 'JUGP156';
UPDATE valuation_items SET subcategory_id = 28, category_id = 3 WHERE id = 510;
UPDATE inventario SET id = 'BANP002' WHERE id = 'JUGP157';
UPDATE valuation_items SET subcategory_id = 39, category_id = 5 WHERE id = 514;
UPDATE inventario SET id = 'HCCP001' WHERE id = 'JUGP159';
UPDATE valuation_items SET subcategory_id = 39, category_id = 5 WHERE id = 515;
UPDATE inventario SET id = 'HCCP002' WHERE id = 'JUGP160';
UPDATE valuation_items SET subcategory_id = 43, category_id = 5 WHERE id = 516;
UPDATE inventario SET id = 'CHNP003' WHERE id = 'JUGP161';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 517;
UPDATE inventario SET id = 'MCCP005' WHERE id = 'JUGP162';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 518;
UPDATE inventario SET id = 'DISP023' WHERE id = 'JUGP163';
UPDATE valuation_items SET subcategory_id = 21, category_id = 3 WHERE id = 523;
UPDATE inventario SET id = 'MCBP004' WHERE id = 'JUGP165';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 524;
UPDATE inventario SET id = 'MCCP006' WHERE id = 'JUGP166';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 525;
UPDATE inventario SET id = 'MCCP007' WHERE id = 'JUGP167';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 526;
UPDATE inventario SET id = 'MCCP008' WHERE id = 'JUGP168';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 527;
UPDATE inventario SET id = 'MCCP009' WHERE id = 'JUGP169';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 528;
UPDATE inventario SET id = 'MCCP010' WHERE id = 'JUGP170';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 529;
UPDATE inventario SET id = 'MCCP011' WHERE id = 'JUGP171';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 530;
UPDATE inventario SET id = 'MCCP012' WHERE id = 'JUGP172';
UPDATE valuation_items SET subcategory_id = 39, category_id = 5 WHERE id = 531;
UPDATE inventario SET id = 'HCCP003' WHERE id = 'JUGP173';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 535;
UPDATE inventario SET id = 'CAPP006' WHERE id = 'JUGP174';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 541;
UPDATE inventario SET id = 'CAPP007' WHERE id = 'JUGP175';
UPDATE valuation_items SET subcategory_id = 34, category_id = 4 WHERE id = 544;
UPDATE inventario SET id = 'PDAP002' WHERE id = 'JUGP177';
UPDATE valuation_items SET subcategory_id = 34, category_id = 4 WHERE id = 545;
UPDATE inventario SET id = 'PDAP003' WHERE id = 'JUGP178';
UPDATE valuation_items SET subcategory_id = 32, category_id = 4 WHERE id = 547;
UPDATE inventario SET id = 'EDBP003' WHERE id = 'JUGP179';
UPDATE valuation_items SET subcategory_id = 32, category_id = 4 WHERE id = 548;
UPDATE inventario SET id = 'EDBP004' WHERE id = 'JUGP180';
UPDATE valuation_items SET subcategory_id = 32, category_id = 4 WHERE id = 549;
UPDATE inventario SET id = 'EDBP005' WHERE id = 'JUGP181';
UPDATE valuation_items SET subcategory_id = 32, category_id = 4 WHERE id = 550;
UPDATE inventario SET id = 'EDBP006' WHERE id = 'JUGP182';
UPDATE valuation_items SET subcategory_id = 32, category_id = 4 WHERE id = 552;
UPDATE inventario SET id = 'EDBP007' WHERE id = 'JUGP183';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 553;
UPDATE inventario SET id = 'EDLP016' WHERE id = 'JUGP184';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 554;
UPDATE inventario SET id = 'EDLP017' WHERE id = 'JUGP185';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 555;
UPDATE inventario SET id = 'EDLP018' WHERE id = 'JUGP186';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 556;
UPDATE inventario SET id = 'EDLP019' WHERE id = 'JUGP187';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 557;
UPDATE inventario SET id = 'EDLP020' WHERE id = 'JUGP188';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 558;
UPDATE inventario SET id = 'EDLP021' WHERE id = 'JUGP189';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 559;
UPDATE inventario SET id = 'EDLP022' WHERE id = 'JUGP190';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 560;
UPDATE inventario SET id = 'EDLP023' WHERE id = 'JUGP191';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 561;
UPDATE inventario SET id = 'ADAP002' WHERE id = 'JUGP192';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 562;
UPDATE inventario SET id = 'ADAP003' WHERE id = 'JUGP193';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 563;
UPDATE inventario SET id = 'ADAP004' WHERE id = 'JUGP194';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 564;
UPDATE inventario SET id = 'ADAP005' WHERE id = 'JUGP195';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 565;
UPDATE inventario SET id = 'EDLP024' WHERE id = 'JUGP196';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 566;
UPDATE inventario SET id = 'ADAP006' WHERE id = 'JUGP197';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 567;
UPDATE inventario SET id = 'EDLP025' WHERE id = 'JUGP198';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 568;
UPDATE inventario SET id = 'ACAP004' WHERE id = 'JUGP199';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 571;
UPDATE inventario SET id = 'CAPP008' WHERE id = 'JUGP200';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 572;
UPDATE inventario SET id = 'CAPP009' WHERE id = 'JUGP201';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 573;
UPDATE inventario SET id = 'CAPP010' WHERE id = 'JUGP202';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 574;
UPDATE inventario SET id = 'CAPP011' WHERE id = 'JUGP203';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 575;
UPDATE inventario SET id = 'ACAP005' WHERE id = 'JUGP204';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 576;
UPDATE inventario SET id = 'ACAP006' WHERE id = 'JUGP205';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 577;
UPDATE inventario SET id = 'CAPP012' WHERE id = 'JUGP206';
UPDATE valuation_items SET subcategory_id = 11, category_id = 2 WHERE id = 578;
UPDATE inventario SET id = 'CYMP002' WHERE id = 'JUGP207';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 579;
UPDATE inventario SET id = 'ADAP007' WHERE id = 'JUGP208';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 580;
UPDATE inventario SET id = 'ADAP008' WHERE id = 'JUGP209';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 581;
UPDATE inventario SET id = 'ADAP009' WHERE id = 'JUGP210';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 583;
UPDATE inventario SET id = 'ACRP006' WHERE id = 'JUGP211';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 585;
UPDATE inventario SET id = 'CAPP013' WHERE id = 'JUGP212';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 587;
UPDATE inventario SET id = 'DISP024' WHERE id = 'JUGP213';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 590;
UPDATE inventario SET id = 'TYBP008' WHERE id = 'JUGP214';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 594;
UPDATE inventario SET id = 'SORP005' WHERE id = 'JUGP215';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 595;
UPDATE inventario SET id = 'SORP006' WHERE id = 'JUGP216';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 596;
UPDATE inventario SET id = 'SORP007' WHERE id = 'JUGP217';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 597;
UPDATE inventario SET id = 'SORP008' WHERE id = 'JUGP218';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 598;
UPDATE inventario SET id = 'SORP009' WHERE id = 'JUGP219';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 599;
UPDATE inventario SET id = 'SORP010' WHERE id = 'JUGP220';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 600;
UPDATE inventario SET id = 'SORP011' WHERE id = 'JUGP221';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 601;
UPDATE inventario SET id = 'ADAP010' WHERE id = 'JUGP222';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 602;
UPDATE inventario SET id = 'ACAP007' WHERE id = 'JUGP223';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 604;
UPDATE inventario SET id = 'ACRP007' WHERE id = 'JUGP224';
UPDATE valuation_items SET subcategory_id = 11, category_id = 2 WHERE id = 608;
UPDATE inventario SET id = 'CYMP003' WHERE id = 'JUGP225';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 615;
UPDATE inventario SET id = 'MCCP013' WHERE id = 'JUGP229';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 616;
UPDATE inventario SET id = 'ADAP011' WHERE id = 'JUGP230';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 617;
UPDATE inventario SET id = 'ADAP012' WHERE id = 'JUGP231';
UPDATE valuation_items SET subcategory_id = 50, category_id = 6 WHERE id = 622;
UPDATE inventario SET id = 'LYRP009' WHERE id = 'JUGP234';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 623;
UPDATE inventario SET id = 'EDLP026' WHERE id = 'JUGP235';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 624;
UPDATE inventario SET id = 'MCCP014' WHERE id = 'JUGP236';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 625;
UPDATE inventario SET id = 'MCCP015' WHERE id = 'JUGP237';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 626;
UPDATE inventario SET id = 'MCCP016' WHERE id = 'JUGP238';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 627;
UPDATE inventario SET id = 'MCCP017' WHERE id = 'JUGP239';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 628;
UPDATE inventario SET id = 'MCCP018' WHERE id = 'JUGP240';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 629;
UPDATE inventario SET id = 'MCCP019' WHERE id = 'JUGP241';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 630;
UPDATE inventario SET id = 'MCCP020' WHERE id = 'JUGP242';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 631;
UPDATE inventario SET id = 'MCCP021' WHERE id = 'JUGP243';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 632;
UPDATE inventario SET id = 'MCCP022' WHERE id = 'JUGP244';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 634;
UPDATE inventario SET id = 'SORP012' WHERE id = 'JUGP245';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 635;
UPDATE inventario SET id = 'SORP013' WHERE id = 'JUGP246';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 636;
UPDATE inventario SET id = 'TYBP009' WHERE id = 'JUGP247';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 637;
UPDATE inventario SET id = 'TYBP010' WHERE id = 'JUGP248';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 638;
UPDATE inventario SET id = 'ADAP013' WHERE id = 'JUGP249';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 639;
UPDATE inventario SET id = 'ADAP014' WHERE id = 'JUGP250';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 640;
UPDATE inventario SET id = 'ADAP015' WHERE id = 'JUGP251';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 642;
UPDATE inventario SET id = 'ADAP016' WHERE id = 'JUGP252';
UPDATE valuation_items SET subcategory_id = 32, category_id = 4 WHERE id = 643;
UPDATE inventario SET id = 'EDBP008' WHERE id = 'JUGP253';
UPDATE valuation_items SET subcategory_id = 21, category_id = 3 WHERE id = 649;
UPDATE inventario SET id = 'MCBP005' WHERE id = 'JUGP255';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 653;
UPDATE inventario SET id = 'ADAP017' WHERE id = 'JUGP256';
UPDATE valuation_items SET subcategory_id = 35, category_id = 4 WHERE id = 654;
UPDATE inventario SET id = 'ADAP018' WHERE id = 'JUGP257';
UPDATE valuation_items SET subcategory_id = 38, category_id = 5 WHERE id = 660;
UPDATE inventario SET id = 'MBCP003' WHERE id = 'JUGP261';
UPDATE valuation_items SET subcategory_id = 38, category_id = 5 WHERE id = 661;
UPDATE inventario SET id = 'MBCP004' WHERE id = 'JUGP262';
UPDATE valuation_items SET subcategory_id = 40, category_id = 5 WHERE id = 662;
UPDATE inventario SET id = 'HACP002' WHERE id = 'JUGP263';
UPDATE valuation_items SET subcategory_id = 40, category_id = 5 WHERE id = 663;
UPDATE inventario SET id = 'HACP003' WHERE id = 'JUGP264';
UPDATE valuation_items SET subcategory_id = 40, category_id = 5 WHERE id = 664;
UPDATE inventario SET id = 'HACP004' WHERE id = 'JUGP265';
UPDATE valuation_items SET subcategory_id = 40, category_id = 5 WHERE id = 665;
UPDATE inventario SET id = 'HACP005' WHERE id = 'JUGP266';
UPDATE valuation_items SET subcategory_id = 40, category_id = 5 WHERE id = 666;
UPDATE inventario SET id = 'HACP006' WHERE id = 'JUGP267';
UPDATE valuation_items SET subcategory_id = 40, category_id = 5 WHERE id = 667;
UPDATE inventario SET id = 'HACP007' WHERE id = 'JUGP268';
UPDATE valuation_items SET subcategory_id = 40, category_id = 5 WHERE id = 668;
UPDATE inventario SET id = 'HACP008' WHERE id = 'JUGP269';
UPDATE valuation_items SET subcategory_id = 39, category_id = 5 WHERE id = 669;
UPDATE inventario SET id = 'HCCP004' WHERE id = 'JUGP270';
UPDATE valuation_items SET subcategory_id = 39, category_id = 5 WHERE id = 670;
UPDATE inventario SET id = 'HCCP005' WHERE id = 'JUGP271';
UPDATE valuation_items SET subcategory_id = 39, category_id = 5 WHERE id = 671;
UPDATE inventario SET id = 'HCCP006' WHERE id = 'JUGP272';
UPDATE valuation_items SET subcategory_id = 39, category_id = 5 WHERE id = 672;
UPDATE inventario SET id = 'HCCP007' WHERE id = 'JUGP273';
UPDATE valuation_items SET subcategory_id = 39, category_id = 5 WHERE id = 673;
UPDATE inventario SET id = 'HCCP008' WHERE id = 'JUGP274';
UPDATE valuation_items SET subcategory_id = 39, category_id = 5 WHERE id = 674;
UPDATE inventario SET id = 'HCCP009' WHERE id = 'JUGP275';
UPDATE valuation_items SET subcategory_id = 42, category_id = 5 WHERE id = 678;
UPDATE inventario SET id = 'CMNP003' WHERE id = 'JUGP278';
UPDATE valuation_items SET subcategory_id = 42, category_id = 5 WHERE id = 679;
UPDATE inventario SET id = 'CMNP004' WHERE id = 'JUGP279';
UPDATE valuation_items SET subcategory_id = 42, category_id = 5 WHERE id = 680;
UPDATE inventario SET id = 'CMNP005' WHERE id = 'JUGP280';
UPDATE valuation_items SET subcategory_id = 42, category_id = 5 WHERE id = 681;
UPDATE inventario SET id = 'CMNP006' WHERE id = 'JUGP281';
UPDATE valuation_items SET subcategory_id = 38, category_id = 5 WHERE id = 682;
UPDATE inventario SET id = 'MBCP005' WHERE id = 'JUGP282';
UPDATE valuation_items SET subcategory_id = 37, category_id = 5 WHERE id = 683;
UPDATE inventario SET id = 'MACP004' WHERE id = 'JUGP283';
UPDATE valuation_items SET subcategory_id = 37, category_id = 5 WHERE id = 684;
UPDATE inventario SET id = 'MACP005' WHERE id = 'JUGP284';
UPDATE valuation_items SET subcategory_id = 37, category_id = 5 WHERE id = 685;
UPDATE inventario SET id = 'MACP006' WHERE id = 'JUGP285';
UPDATE valuation_items SET subcategory_id = 37, category_id = 5 WHERE id = 686;
UPDATE inventario SET id = 'MACP007' WHERE id = 'JUGP286';
UPDATE valuation_items SET subcategory_id = 37, category_id = 5 WHERE id = 687;
UPDATE inventario SET id = 'MACP008' WHERE id = 'JUGP287';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 688;
UPDATE inventario SET id = 'MCCP023' WHERE id = 'JUGP288';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 689;
UPDATE inventario SET id = 'MCCP024' WHERE id = 'JUGP289';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 690;
UPDATE inventario SET id = 'MCCP025' WHERE id = 'JUGP290';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 691;
UPDATE inventario SET id = 'MCCP026' WHERE id = 'JUGP291';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 692;
UPDATE inventario SET id = 'ANDP007' WHERE id = 'JUGP292';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 693;
UPDATE inventario SET id = 'JDMP007' WHERE id = 'JUGP293';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 694;
UPDATE inventario SET id = 'JDMP008' WHERE id = 'JUGP294';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 697;
UPDATE inventario SET id = 'SORP014' WHERE id = 'JUGP297';
UPDATE valuation_items SET subcategory_id = 34, category_id = 4 WHERE id = 698;
UPDATE inventario SET id = 'PDAP004' WHERE id = 'JUGP298';
UPDATE valuation_items SET subcategory_id = 28, category_id = 3 WHERE id = 702;
UPDATE inventario SET id = 'BANP003' WHERE id = 'JUGP299';
UPDATE valuation_items SET subcategory_id = 43, category_id = 5 WHERE id = 703;
UPDATE inventario SET id = 'CHNP004' WHERE id = 'JUGP300';
UPDATE valuation_items SET subcategory_id = 43, category_id = 5 WHERE id = 704;
UPDATE inventario SET id = 'CHNP005' WHERE id = 'JUGP301';
UPDATE valuation_items SET subcategory_id = 43, category_id = 5 WHERE id = 705;
UPDATE inventario SET id = 'CHNP006' WHERE id = 'JUGP302';
UPDATE valuation_items SET subcategory_id = 43, category_id = 5 WHERE id = 706;
UPDATE inventario SET id = 'CHNP007' WHERE id = 'JUGP303';
UPDATE valuation_items SET subcategory_id = 14, category_id = 2 WHERE id = 712;
UPDATE inventario SET id = 'COLP003' WHERE id = 'JUGP304';
UPDATE valuation_items SET subcategory_id = 11, category_id = 2 WHERE id = 713;
UPDATE inventario SET id = 'CYMP004' WHERE id = 'JUGP305';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 720;
UPDATE inventario SET id = 'SORP015' WHERE id = 'JUGP310';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 721;
UPDATE inventario SET id = 'TYBP011' WHERE id = 'JUGP311';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 722;
UPDATE inventario SET id = 'ACRP008' WHERE id = 'JUGP312';
UPDATE valuation_items SET subcategory_id = 14, category_id = 2 WHERE id = 723;
UPDATE inventario SET id = 'COLP004' WHERE id = 'JUGP313';
UPDATE valuation_items SET subcategory_id = 13, category_id = 2 WHERE id = 724;
UPDATE inventario SET id = 'JDCP002' WHERE id = 'JUGP314';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 725;
UPDATE inventario SET id = 'DISP025' WHERE id = 'JUGP315';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 729;
UPDATE inventario SET id = 'ACAP008' WHERE id = 'JUGP319';
UPDATE valuation_items SET subcategory_id = 54, category_id = 6 WHERE id = 731;
UPDATE inventario SET id = 'MDEP005' WHERE id = 'JUGP320';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 732;
UPDATE inventario SET id = 'SORP016' WHERE id = 'JUGP321';
UPDATE valuation_items SET subcategory_id = 28, category_id = 3 WHERE id = 733;
UPDATE inventario SET id = 'BANP004' WHERE id = 'JUGP322';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 734;
UPDATE inventario SET id = 'ABDP028' WHERE id = 'JUGP323';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 735;
UPDATE inventario SET id = 'ABDP029' WHERE id = 'JUGP324';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 741;
UPDATE inventario SET id = 'TYBP012' WHERE id = 'JUGP327';
UPDATE valuation_items SET subcategory_id = 28, category_id = 3 WHERE id = 742;
UPDATE inventario SET id = 'BANP005' WHERE id = 'JUGP328';
UPDATE valuation_items SET subcategory_id = 21, category_id = 3 WHERE id = 743;
UPDATE inventario SET id = 'MCBP006' WHERE id = 'JUGP329';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 748;
UPDATE inventario SET id = 'ANDP008' WHERE id = 'JUGP330';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 750;
UPDATE inventario SET id = 'ACAP009' WHERE id = 'JUGP332';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 751;
UPDATE inventario SET id = 'ACAP010' WHERE id = 'JUGP333';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 752;
UPDATE inventario SET id = 'ACAP011' WHERE id = 'JUGP334';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 753;
UPDATE inventario SET id = 'ACAP012' WHERE id = 'JUGP335';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 755;
UPDATE inventario SET id = 'CAPP014' WHERE id = 'JUGP336';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 756;
UPDATE inventario SET id = 'CAPP015' WHERE id = 'JUGP337';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 757;
UPDATE inventario SET id = 'CAPP016' WHERE id = 'JUGP338';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 758;
UPDATE inventario SET id = 'SORP017' WHERE id = 'JUGP339';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 759;
UPDATE inventario SET id = 'SORP018' WHERE id = 'JUGP340';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 760;
UPDATE inventario SET id = 'ABDP030' WHERE id = 'JUGP341';
UPDATE valuation_items SET subcategory_id = 44, category_id = 5 WHERE id = 761;
UPDATE inventario SET id = 'ABDP031' WHERE id = 'JUGP342';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 763;
UPDATE inventario SET id = 'EDLP027' WHERE id = 'JUGP343';
UPDATE valuation_items SET subcategory_id = 21, category_id = 3 WHERE id = 764;
UPDATE inventario SET id = 'MCBP007' WHERE id = 'JUGP344';
UPDATE valuation_items SET subcategory_id = 32, category_id = 4 WHERE id = 765;
UPDATE inventario SET id = 'EDBP009' WHERE id = 'JUGP345';
UPDATE valuation_items SET subcategory_id = 32, category_id = 4 WHERE id = 767;
UPDATE inventario SET id = 'EDBP010' WHERE id = 'JUGP346';
UPDATE valuation_items SET subcategory_id = 16, category_id = 2 WHERE id = 769;
UPDATE inventario SET id = 'MDCP007' WHERE id = 'JUGP347';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 770;
UPDATE inventario SET id = 'ACAP013' WHERE id = 'JUGP348';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 771;
UPDATE inventario SET id = 'ACAP014' WHERE id = 'JUGP349';
UPDATE valuation_items SET subcategory_id = 13, category_id = 2 WHERE id = 772;
UPDATE inventario SET id = 'JDCP003' WHERE id = 'JUGP350';
UPDATE valuation_items SET subcategory_id = 28, category_id = 3 WHERE id = 775;
UPDATE inventario SET id = 'BANP006' WHERE id = 'JUGP352';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 776;
UPDATE inventario SET id = 'ANDP009' WHERE id = 'JUGP353';
UPDATE valuation_items SET subcategory_id = 21, category_id = 3 WHERE id = 777;
UPDATE inventario SET id = 'MCBP008' WHERE id = 'JUGP354';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 783;
UPDATE inventario SET id = 'CAPP017' WHERE id = 'JUGP356';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 786;
UPDATE inventario SET id = 'JDMP009' WHERE id = 'JUGP357';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 789;
UPDATE inventario SET id = 'EDLP028' WHERE id = 'JUGP358';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 791;
UPDATE inventario SET id = 'ANDP010' WHERE id = 'JUGP359';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 795;
UPDATE inventario SET id = 'SORP019' WHERE id = 'JUGP362';
UPDATE valuation_items SET subcategory_id = 28, category_id = 3 WHERE id = 796;
UPDATE inventario SET id = 'BANP007' WHERE id = 'JUGP363';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 797;
UPDATE inventario SET id = 'TYBP013' WHERE id = 'JUGP364';
UPDATE valuation_items SET subcategory_id = 21, category_id = 3 WHERE id = 799;
UPDATE inventario SET id = 'MCBP009' WHERE id = 'JUGP365';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 809;
UPDATE inventario SET id = 'CAPP018' WHERE id = 'JUGP372';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 810;
UPDATE inventario SET id = 'JDMP010' WHERE id = 'JUGP373';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 812;
UPDATE inventario SET id = 'JDMP011' WHERE id = 'JUGP374';
UPDATE valuation_items SET subcategory_id = 11, category_id = 2 WHERE id = 818;
UPDATE inventario SET id = 'CYMP005' WHERE id = 'JUGP379';
UPDATE valuation_items SET subcategory_id = 53, category_id = 6 WHERE id = 819;
UPDATE inventario SET id = 'MCRP012' WHERE id = 'JUGP380';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 820;
UPDATE inventario SET id = 'SORP020' WHERE id = 'JUGP381';
UPDATE valuation_items SET subcategory_id = 11, category_id = 2 WHERE id = 824;
UPDATE inventario SET id = 'CYMP006' WHERE id = 'JUGP382';
UPDATE valuation_items SET subcategory_id = 16, category_id = 2 WHERE id = 826;
UPDATE inventario SET id = 'MDCP008' WHERE id = 'JUGP383';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 827;
UPDATE inventario SET id = 'DISP026' WHERE id = 'JUGP384';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 828;
UPDATE inventario SET id = 'DISP027' WHERE id = 'JUGP385';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 829;
UPDATE inventario SET id = 'DISP028' WHERE id = 'JUGP386';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 830;
UPDATE inventario SET id = 'DISP029' WHERE id = 'JUGP387';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 831;
UPDATE inventario SET id = 'DISP030' WHERE id = 'JUGP388';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 832;
UPDATE inventario SET id = 'DISP031' WHERE id = 'JUGP389';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 833;
UPDATE inventario SET id = 'DISP032' WHERE id = 'JUGP390';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 834;
UPDATE inventario SET id = 'DISP033' WHERE id = 'JUGP391';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 835;
UPDATE inventario SET id = 'DISP034' WHERE id = 'JUGP392';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 836;
UPDATE inventario SET id = 'DISP035' WHERE id = 'JUGP393';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 837;
UPDATE inventario SET id = 'DISP036' WHERE id = 'JUGP394';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 838;
UPDATE inventario SET id = 'DISP037' WHERE id = 'JUGP395';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 839;
UPDATE inventario SET id = 'DISP038' WHERE id = 'JUGP396';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 842;
UPDATE inventario SET id = 'CAPP019' WHERE id = 'JUGP397';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 847;
UPDATE inventario SET id = 'EDLP029' WHERE id = 'JUGP400';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 848;
UPDATE inventario SET id = 'ACRP009' WHERE id = 'JUGP401';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 850;
UPDATE inventario SET id = 'DISP039' WHERE id = 'JUGP402';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 851;
UPDATE inventario SET id = 'DISP040' WHERE id = 'JUGP403';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 852;
UPDATE inventario SET id = 'DISP041' WHERE id = 'JUGP404';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 853;
UPDATE inventario SET id = 'DISP042' WHERE id = 'JUGP405';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 854;
UPDATE inventario SET id = 'DISP043' WHERE id = 'JUGP406';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 855;
UPDATE inventario SET id = 'DISP044' WHERE id = 'JUGP407';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 856;
UPDATE inventario SET id = 'DISP045' WHERE id = 'JUGP408';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 857;
UPDATE inventario SET id = 'DISP046' WHERE id = 'JUGP409';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 858;
UPDATE inventario SET id = 'DISP047' WHERE id = 'JUGP410';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 860;
UPDATE inventario SET id = 'JDMP012' WHERE id = 'JUGP411';
UPDATE valuation_items SET subcategory_id = 4, category_id = 1 WHERE id = 861;
UPDATE inventario SET id = 'ACAP015' WHERE id = 'JUGP412';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 864;
UPDATE inventario SET id = 'TYBP014' WHERE id = 'JUGP413';
UPDATE valuation_items SET subcategory_id = 42, category_id = 5 WHERE id = 870;
UPDATE inventario SET id = 'CMNP007' WHERE id = 'JUGP415';
UPDATE valuation_items SET subcategory_id = 42, category_id = 5 WHERE id = 871;
UPDATE inventario SET id = 'CMNP008' WHERE id = 'JUGP416';
UPDATE valuation_items SET subcategory_id = 42, category_id = 5 WHERE id = 872;
UPDATE inventario SET id = 'CMNP009' WHERE id = 'JUGP417';
UPDATE valuation_items SET subcategory_id = 42, category_id = 5 WHERE id = 873;
UPDATE inventario SET id = 'CMNP010' WHERE id = 'JUGP418';
UPDATE valuation_items SET subcategory_id = 36, category_id = 5 WHERE id = 874;
UPDATE inventario SET id = 'MCCP027' WHERE id = 'JUGP419';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 875;
UPDATE inventario SET id = 'ACRP010' WHERE id = 'JUGP420';
UPDATE valuation_items SET subcategory_id = 52, category_id = 6 WHERE id = 876;
UPDATE inventario SET id = 'ANDP011' WHERE id = 'JUGP421';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 877;
UPDATE inventario SET id = 'DISP048' WHERE id = 'JUGP422';
UPDATE valuation_items SET subcategory_id = 47, category_id = 6 WHERE id = 878;
UPDATE inventario SET id = 'DISP049' WHERE id = 'JUGP423';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 879;
UPDATE inventario SET id = 'JDMP013' WHERE id = 'JUGP424';
UPDATE valuation_items SET subcategory_id = 48, category_id = 6 WHERE id = 880;
UPDATE inventario SET id = 'JDMP014' WHERE id = 'JUGP425';
UPDATE valuation_items SET subcategory_id = 42, category_id = 5 WHERE id = 888;
UPDATE inventario SET id = 'CMNP011' WHERE id = 'JUGP428';
UPDATE valuation_items SET subcategory_id = 33, category_id = 4 WHERE id = 889;
UPDATE inventario SET id = 'EDLP030' WHERE id = 'JUGP429';
UPDATE valuation_items SET subcategory_id = 19, category_id = 2 WHERE id = 890;
UPDATE inventario SET id = 'ACRP011' WHERE id = 'JUGP430';
UPDATE valuation_items SET subcategory_id = 11, category_id = 2 WHERE id = 891;
UPDATE inventario SET id = 'CYMP007' WHERE id = 'JUGP431';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 899;
UPDATE inventario SET id = 'CAPP020' WHERE id = 'JUGP436';
UPDATE valuation_items SET subcategory_id = 2, category_id = 1 WHERE id = 900;
UPDATE inventario SET id = 'CAPP021' WHERE id = 'JUGP437';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 901;
UPDATE inventario SET id = 'SORP021' WHERE id = 'JUGP438';
UPDATE valuation_items SET subcategory_id = 8, category_id = 1 WHERE id = 902;
UPDATE inventario SET id = 'SORP022' WHERE id = 'JUGP439';
UPDATE valuation_items SET subcategory_id = 6, category_id = 1 WHERE id = 903;
UPDATE inventario SET id = 'TYBP015' WHERE id = 'JUGP440';
UPDATE valuation_items SET subcategory_id = 43, category_id = 5 WHERE id = 905;
UPDATE inventario SET id = 'CHNP008' WHERE id = 'JUGP442';

COMMIT;
