-- Migration: Add clothing valuation prices table
-- This table stores fixed purchase prices for clothing items based on garment type and quality level

-- Create clothing_valuation_prices table
CREATE TABLE IF NOT EXISTS clothing_valuation_prices (
  id SERIAL PRIMARY KEY,
  category_group VARCHAR(50) NOT NULL, -- 'cuerpo_completo', 'arriba_cintura', 'abajo_cintura', 'calzado', 'dama_maternidad'
  garment_type VARCHAR(100) NOT NULL, -- e.g., 'Abrigo', 'Playera/Blusa Mcorta', etc.
  quality_level VARCHAR(20) NOT NULL, -- 'economico', 'estandar', 'alto', 'premium'
  purchase_price NUMERIC(10,2) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX idx_clothing_prices_category_group ON clothing_valuation_prices(category_group);
CREATE INDEX idx_clothing_prices_garment_type ON clothing_valuation_prices(garment_type);
CREATE INDEX idx_clothing_prices_quality ON clothing_valuation_prices(quality_level);
CREATE INDEX idx_clothing_prices_active ON clothing_valuation_prices(is_active) WHERE is_active = TRUE;

-- Add is_clothing flag to subcategories to identify clothing categories
ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS is_clothing BOOLEAN DEFAULT FALSE;

-- Update existing clothing subcategories
UPDATE subcategories SET is_clothing = TRUE WHERE category_id = 5;

-- Insert clothing valuation prices data
-- Cuerpo completo
INSERT INTO clothing_valuation_prices (category_group, garment_type, quality_level, purchase_price) VALUES
('cuerpo_completo', 'Abrigo', 'economico', 40),
('cuerpo_completo', 'Abrigo', 'estandar', 70),
('cuerpo_completo', 'Abrigo', 'alto', 130),
('cuerpo_completo', 'Abrigo', 'premium', 170),
('cuerpo_completo', 'Bata', 'economico', 15),
('cuerpo_completo', 'Bata', 'estandar', 20),
('cuerpo_completo', 'Bata', 'alto', 40),
('cuerpo_completo', 'Bata', 'premium', 60),
('cuerpo_completo', 'Bata de baño', 'economico', 20),
('cuerpo_completo', 'Bata de baño', 'estandar', 30),
('cuerpo_completo', 'Bata de baño', 'alto', 50),
('cuerpo_completo', 'Bata de baño', 'premium', 90),
('cuerpo_completo', 'Traje', 'economico', 35),
('cuerpo_completo', 'Traje', 'estandar', 60),
('cuerpo_completo', 'Traje', 'alto', 110),
('cuerpo_completo', 'Traje', 'premium', 130),
('cuerpo_completo', 'Comando grueso', 'economico', 40),
('cuerpo_completo', 'Comando grueso', 'estandar', 60),
('cuerpo_completo', 'Comando grueso', 'alto', 100),
('cuerpo_completo', 'Comando grueso', 'premium', 125),
('cuerpo_completo', 'Comando ligero', 'economico', 35),
('cuerpo_completo', 'Comando ligero', 'estandar', 50),
('cuerpo_completo', 'Comando ligero', 'alto', 90),
('cuerpo_completo', 'Comando ligero', 'premium', 120),
('cuerpo_completo', 'Conjunto bebes', 'economico', 20),
('cuerpo_completo', 'Conjunto bebes', 'estandar', 30),
('cuerpo_completo', 'Conjunto bebes', 'alto', 50),
('cuerpo_completo', 'Conjunto bebes', 'premium', 80),
('cuerpo_completo', 'Conjunto', 'economico', 40),
('cuerpo_completo', 'Conjunto', 'estandar', 50),
('cuerpo_completo', 'Conjunto', 'alto', 100),
('cuerpo_completo', 'Conjunto', 'premium', 150),
('cuerpo_completo', 'Costalito', 'economico', 20),
('cuerpo_completo', 'Costalito', 'estandar', 40),
('cuerpo_completo', 'Costalito', 'alto', 100),
('cuerpo_completo', 'Costalito', 'premium', 120),
('cuerpo_completo', 'Gabardina', 'economico', 40),
('cuerpo_completo', 'Gabardina', 'estandar', 60),
('cuerpo_completo', 'Gabardina', 'alto', 100),
('cuerpo_completo', 'Gabardina', 'premium', 150),
('cuerpo_completo', 'Impermeable', 'economico', 20),
('cuerpo_completo', 'Impermeable', 'estandar', 40),
('cuerpo_completo', 'Impermeable', 'alto', 90),
('cuerpo_completo', 'Impermeable', 'premium', 130),
('cuerpo_completo', 'Mameluco', 'economico', 15),
('cuerpo_completo', 'Mameluco', 'estandar', 20),
('cuerpo_completo', 'Mameluco', 'alto', 60),
('cuerpo_completo', 'Mameluco', 'premium', 90),
('cuerpo_completo', 'Overall', 'economico', 30),
('cuerpo_completo', 'Overall', 'estandar', 40),
('cuerpo_completo', 'Overall', 'alto', 65),
('cuerpo_completo', 'Overall', 'premium', 90),
('cuerpo_completo', 'Pants completo', 'economico', 50),
('cuerpo_completo', 'Pants completo', 'estandar', 60),
('cuerpo_completo', 'Pants completo', 'alto', 120),
('cuerpo_completo', 'Pants completo', 'premium', 150),
('cuerpo_completo', 'Pañalero exterior', 'economico', 10),
('cuerpo_completo', 'Pañalero exterior', 'estandar', 15),
('cuerpo_completo', 'Pañalero exterior', 'alto', 30),
('cuerpo_completo', 'Pañalero exterior', 'premium', 50),
('cuerpo_completo', 'Pañalero interior', 'economico', 5),
('cuerpo_completo', 'Pañalero interior', 'estandar', 6),
('cuerpo_completo', 'Pañalero interior', 'alto', 15),
('cuerpo_completo', 'Pañalero interior', 'premium', 30),
('cuerpo_completo', 'Pijama corta', 'economico', 20),
('cuerpo_completo', 'Pijama corta', 'estandar', 30),
('cuerpo_completo', 'Pijama corta', 'alto', 60),
('cuerpo_completo', 'Pijama corta', 'premium', 80),
('cuerpo_completo', 'Pijama larga', 'economico', 20),
('cuerpo_completo', 'Pijama larga', 'estandar', 35),
('cuerpo_completo', 'Pijama larga', 'alto', 70),
('cuerpo_completo', 'Pijama larga', 'premium', 100),
('cuerpo_completo', 'Traje Baño Completo', 'economico', 30),
('cuerpo_completo', 'Traje Baño Completo', 'estandar', 40),
('cuerpo_completo', 'Traje Baño Completo', 'alto', 70),
('cuerpo_completo', 'Traje Baño Completo', 'premium', 100),
('cuerpo_completo', 'Vestido niña', 'economico', 30),
('cuerpo_completo', 'Vestido niña', 'estandar', 40),
('cuerpo_completo', 'Vestido niña', 'alto', 100),
('cuerpo_completo', 'Vestido niña', 'premium', 130),
('cuerpo_completo', 'Vestido bebé', 'economico', 20),
('cuerpo_completo', 'Vestido bebé', 'estandar', 30),
('cuerpo_completo', 'Vestido bebé', 'alto', 60),
('cuerpo_completo', 'Vestido bebé', 'premium', 100),
('cuerpo_completo', 'Vestido de fiesta', 'economico', 40),
('cuerpo_completo', 'Vestido de fiesta', 'estandar', 60),
('cuerpo_completo', 'Vestido de fiesta', 'alto', 120),
('cuerpo_completo', 'Vestido de fiesta', 'premium', 150);

-- Arriba de cintura
INSERT INTO clothing_valuation_prices (category_group, garment_type, quality_level, purchase_price) VALUES
('arriba_cintura', 'Playera/Blusa Mcorta', 'economico', 15),
('arriba_cintura', 'Playera/Blusa Mcorta', 'estandar', 20),
('arriba_cintura', 'Playera/Blusa Mcorta', 'alto', 40),
('arriba_cintura', 'Playera/Blusa Mcorta', 'premium', 60),
('arriba_cintura', 'Player/Blusa Mlarga', 'economico', 20),
('arriba_cintura', 'Player/Blusa Mlarga', 'estandar', 25),
('arriba_cintura', 'Player/Blusa Mlarga', 'alto', 50),
('arriba_cintura', 'Player/Blusa Mlarga', 'premium', 80),
('arriba_cintura', 'Camisa Mcorta', 'economico', 20),
('arriba_cintura', 'Camisa Mcorta', 'estandar', 30),
('arriba_cintura', 'Camisa Mcorta', 'alto', 50),
('arriba_cintura', 'Camisa Mcorta', 'premium', 90),
('arriba_cintura', 'Camisa Mlarga', 'economico', 25),
('arriba_cintura', 'Camisa Mlarga', 'estandar', 35),
('arriba_cintura', 'Camisa Mlarga', 'alto', 60),
('arriba_cintura', 'Camisa Mlarga', 'premium', 100),
('arriba_cintura', 'Polos Mlarga', 'economico', 25),
('arriba_cintura', 'Polos Mlarga', 'estandar', 40),
('arriba_cintura', 'Polos Mlarga', 'alto', 90),
('arriba_cintura', 'Polos Mlarga', 'premium', 120),
('arriba_cintura', 'Polos Mcorta', 'economico', 20),
('arriba_cintura', 'Polos Mcorta', 'estandar', 35),
('arriba_cintura', 'Polos Mcorta', 'alto', 70),
('arriba_cintura', 'Polos Mcorta', 'premium', 100),
('arriba_cintura', 'Tirantes', 'economico', 15),
('arriba_cintura', 'Tirantes', 'estandar', 20),
('arriba_cintura', 'Tirantes', 'alto', 40),
('arriba_cintura', 'Tirantes', 'premium', 50),
('arriba_cintura', 'Chaleco Grueso', 'economico', 25),
('arriba_cintura', 'Chaleco Grueso', 'estandar', 35),
('arriba_cintura', 'Chaleco Grueso', 'alto', 70),
('arriba_cintura', 'Chaleco Grueso', 'premium', 100),
('arriba_cintura', 'Chaleco ligero', 'economico', 25),
('arriba_cintura', 'Chaleco ligero', 'estandar', 30),
('arriba_cintura', 'Chaleco ligero', 'alto', 55),
('arriba_cintura', 'Chaleco ligero', 'premium', 80),
('arriba_cintura', 'Cham.ligera/Romp.', 'economico', 30),
('arriba_cintura', 'Cham.ligera/Romp.', 'estandar', 50),
('arriba_cintura', 'Cham.ligera/Romp.', 'alto', 70),
('arriba_cintura', 'Cham.ligera/Romp.', 'premium', 100),
('arriba_cintura', 'Chamarra Gruesa', 'economico', 50),
('arriba_cintura', 'Chamarra Gruesa', 'estandar', 60),
('arriba_cintura', 'Chamarra Gruesa', 'alto', 100),
('arriba_cintura', 'Chamarra Gruesa', 'premium', 150),
('arriba_cintura', 'Chamarra mezclilla', 'economico', 50),
('arriba_cintura', 'Chamarra mezclilla', 'estandar', 60),
('arriba_cintura', 'Chamarra mezclilla', 'alto', 100),
('arriba_cintura', 'Chamarra mezclilla', 'premium', 150),
('arriba_cintura', 'Gorro/Sombrero', 'economico', 5),
('arriba_cintura', 'Gorro/Sombrero', 'estandar', 10),
('arriba_cintura', 'Gorro/Sombrero', 'alto', 30),
('arriba_cintura', 'Gorro/Sombrero', 'premium', 50),
('arriba_cintura', 'Guantes y accesorios', 'economico', 10),
('arriba_cintura', 'Guantes y accesorios', 'estandar', 15),
('arriba_cintura', 'Guantes y accesorios', 'alto', 30),
('arriba_cintura', 'Guantes y accesorios', 'premium', 50),
('arriba_cintura', 'Moños y diademas', 'economico', 5),
('arriba_cintura', 'Moños y diademas', 'estandar', 10),
('arriba_cintura', 'Moños y diademas', 'alto', 30),
('arriba_cintura', 'Moños y diademas', 'premium', 40),
('arriba_cintura', 'Sudadera', 'economico', 30),
('arriba_cintura', 'Sudadera', 'estandar', 40),
('arriba_cintura', 'Sudadera', 'alto', 80),
('arriba_cintura', 'Sudadera', 'premium', 100),
('arriba_cintura', 'Suéter', 'economico', 30),
('arriba_cintura', 'Suéter', 'estandar', 40),
('arriba_cintura', 'Suéter', 'alto', 80),
('arriba_cintura', 'Suéter', 'premium', 100),
('arriba_cintura', 'Torero', 'economico', 20),
('arriba_cintura', 'Torero', 'estandar', 30),
('arriba_cintura', 'Torero', 'alto', 60),
('arriba_cintura', 'Torero', 'premium', 90);

-- Abajo de cintura
INSERT INTO clothing_valuation_prices (category_group, garment_type, quality_level, purchase_price) VALUES
('abajo_cintura', 'Bermuda', 'economico', 15),
('abajo_cintura', 'Bermuda', 'estandar', 20),
('abajo_cintura', 'Bermuda', 'alto', 50),
('abajo_cintura', 'Bermuda', 'premium', 80),
('abajo_cintura', 'Bikini', 'economico', 20),
('abajo_cintura', 'Bikini', 'estandar', 35),
('abajo_cintura', 'Bikini', 'alto', 70),
('abajo_cintura', 'Bikini', 'premium', 90),
('abajo_cintura', 'Calcetas', 'economico', 5),
('abajo_cintura', 'Calcetas', 'estandar', 10),
('abajo_cintura', 'Calcetas', 'alto', 30),
('abajo_cintura', 'Calcetas', 'premium', 50),
('abajo_cintura', 'Accesorios', 'economico', 10),
('abajo_cintura', 'Accesorios', 'estandar', 20),
('abajo_cintura', 'Accesorios', 'alto', 40),
('abajo_cintura', 'Accesorios', 'premium', 50),
('abajo_cintura', 'Falda', 'economico', 15),
('abajo_cintura', 'Falda', 'estandar', 25),
('abajo_cintura', 'Falda', 'alto', 40),
('abajo_cintura', 'Falda', 'premium', 70),
('abajo_cintura', 'Leggins / Mallas', 'economico', 10),
('abajo_cintura', 'Leggins / Mallas', 'estandar', 15),
('abajo_cintura', 'Leggins / Mallas', 'alto', 30),
('abajo_cintura', 'Leggins / Mallas', 'premium', 50),
('abajo_cintura', 'Pantalón Mezclilla', 'economico', 30),
('abajo_cintura', 'Pantalón Mezclilla', 'estandar', 40),
('abajo_cintura', 'Pantalón Mezclilla', 'alto', 70),
('abajo_cintura', 'Pantalón Mezclilla', 'premium', 130),
('abajo_cintura', 'Pantalón Tela', 'economico', 20),
('abajo_cintura', 'Pantalón Tela', 'estandar', 35),
('abajo_cintura', 'Pantalón Tela', 'alto', 60),
('abajo_cintura', 'Pantalón Tela', 'premium', 90),
('abajo_cintura', 'Pants', 'economico', 20),
('abajo_cintura', 'Pants', 'estandar', 35),
('abajo_cintura', 'Pants', 'alto', 60),
('abajo_cintura', 'Pants', 'premium', 90),
('abajo_cintura', 'short', 'economico', 15),
('abajo_cintura', 'short', 'estandar', 25),
('abajo_cintura', 'short', 'alto', 40),
('abajo_cintura', 'short', 'premium', 70),
('abajo_cintura', 'Traje de baño 1pza', 'economico', 20),
('abajo_cintura', 'Traje de baño 1pza', 'estandar', 35),
('abajo_cintura', 'Traje de baño 1pza', 'alto', 70),
('abajo_cintura', 'Traje de baño 1pza', 'premium', 90);

-- Calzado
INSERT INTO clothing_valuation_prices (category_group, garment_type, quality_level, purchase_price) VALUES
('calzado', 'Botas y botines', 'economico', 25),
('calzado', 'Botas y botines', 'estandar', 35),
('calzado', 'Botas y botines', 'alto', 90),
('calzado', 'Botas y botines', 'premium', 150),
('calzado', 'Botas Nieve / Piel', 'economico', 35),
('calzado', 'Botas Nieve / Piel', 'estandar', 50),
('calzado', 'Botas Nieve / Piel', 'alto', 110),
('calzado', 'Botas Nieve / Piel', 'premium', 170),
('calzado', 'Botas lluvia', 'economico', 20),
('calzado', 'Botas lluvia', 'estandar', 25),
('calzado', 'Botas lluvia', 'alto', 50),
('calzado', 'Botas lluvia', 'premium', 100),
('calzado', 'Crocs', 'economico', 30),
('calzado', 'Crocs', 'estandar', 45),
('calzado', 'Crocs', 'alto', 80),
('calzado', 'Crocs', 'premium', 120),
('calzado', 'Huaraches', 'economico', 20),
('calzado', 'Huaraches', 'estandar', 25),
('calzado', 'Huaraches', 'alto', 45),
('calzado', 'Huaraches', 'premium', 60),
('calzado', 'Pantuflas', 'economico', 15),
('calzado', 'Pantuflas', 'estandar', 20),
('calzado', 'Pantuflas', 'alto', 40),
('calzado', 'Pantuflas', 'premium', 50),
('calzado', 'Sandalias', 'economico', 15),
('calzado', 'Sandalias', 'estandar', 20),
('calzado', 'Sandalias', 'alto', 35),
('calzado', 'Sandalias', 'premium', 45),
('calzado', 'Tennis', 'economico', 35),
('calzado', 'Tennis', 'estandar', 50),
('calzado', 'Tennis', 'alto', 100),
('calzado', 'Tennis', 'premium', 130),
('calzado', 'Zapato bebé', 'economico', 15),
('calzado', 'Zapato bebé', 'estandar', 20),
('calzado', 'Zapato bebé', 'alto', 45),
('calzado', 'Zapato bebé', 'premium', 80),
('calzado', 'Zapato niño(a)', 'economico', 25),
('calzado', 'Zapato niño(a)', 'estandar', 35),
('calzado', 'Zapato niño(a)', 'alto', 65),
('calzado', 'Zapato niño(a)', 'premium', 100),
('calzado', 'Botas bebé', 'economico', 20),
('calzado', 'Botas bebé', 'estandar', 25),
('calzado', 'Botas bebé', 'alto', 40),
('calzado', 'Botas bebé', 'premium', 80),
('calzado', 'Zapatillas', 'economico', 20),
('calzado', 'Zapatillas', 'estandar', 35),
('calzado', 'Zapatillas', 'alto', 65),
('calzado', 'Zapatillas', 'premium', 90);

-- Dama/Maternidad (valores ficticios como solicitado)
INSERT INTO clothing_valuation_prices (category_group, garment_type, quality_level, purchase_price) VALUES
('dama_maternidad', 'Blusa Maternidad', 'economico', 25),
('dama_maternidad', 'Blusa Maternidad', 'estandar', 40),
('dama_maternidad', 'Blusa Maternidad', 'alto', 70),
('dama_maternidad', 'Blusa Maternidad', 'premium', 100),
('dama_maternidad', 'Pantalón Maternidad', 'economico', 35),
('dama_maternidad', 'Pantalón Maternidad', 'estandar', 50),
('dama_maternidad', 'Pantalón Maternidad', 'alto', 80),
('dama_maternidad', 'Pantalón Maternidad', 'premium', 120),
('dama_maternidad', 'Vestido Maternidad', 'economico', 40),
('dama_maternidad', 'Vestido Maternidad', 'estandar', 60),
('dama_maternidad', 'Vestido Maternidad', 'alto', 100),
('dama_maternidad', 'Vestido Maternidad', 'premium', 150),
('dama_maternidad', 'Bolsa Dama', 'economico', 50),
('dama_maternidad', 'Bolsa Dama', 'estandar', 80),
('dama_maternidad', 'Bolsa Dama', 'alto', 150),
('dama_maternidad', 'Bolsa Dama', 'premium', 250);

-- Create clothing sizes table for reference
CREATE TABLE IF NOT EXISTS clothing_sizes (
  id SERIAL PRIMARY KEY,
  category_group VARCHAR(50) NOT NULL,
  size_value VARCHAR(50) NOT NULL,
  display_order INTEGER NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- Insert clothing sizes
INSERT INTO clothing_sizes (category_group, size_value, display_order) VALUES
-- Cuerpo completo, Arriba de cintura, Abajo de cintura
('general', '0m', 1),
('general', '3m', 2),
('general', '6m', 3),
('general', '9m', 4),
('general', '12m', 5),
('general', '18m', 6),
('general', '2a', 7),
('general', '3a', 8),
('general', '4a', 9),
('general', '5a', 10),
('general', '6a', 11),
('general', '7a', 12),
('general', '8a', 13),
('general', '9a', 14),
('general', 'Ch 10-11', 15),
('general', 'M 12-13', 16),
('general', 'G 14-15', 17),
-- Calzado
('calzado', '0-6m 8-10cm', 1),
('calzado', '6-9m 10.5-11cm', 2),
('calzado', '9-12m 11.5-12cm', 3),
('calzado', '12-18m 12.5-13cm', 4),
('calzado', '18-24m 13.5-14cm', 5),
('calzado', '2-3a 14.5-15cm', 6),
('calzado', '3-4a 15.5-16cm', 7),
('calzado', '4-5a 16.5-17cm', 8),
('calzado', '5-6a 17.5-18cm', 9),
('calzado', '6-7a 18.5-19cm', 10),
('calzado', '7-8a 19.5-20cm', 11),
('calzado', '21cm', 12),
('calzado', '22cm', 13),
('calzado', '23 cm', 14),
('calzado', '24cm', 15),
('calzado', '25cm', 16),
-- Dama/Maternidad
('dama_maternidad', 'XS', 1),
('dama_maternidad', 'S', 2),
('dama_maternidad', 'M', 3),
('dama_maternidad', 'L', 4),
('dama_maternidad', 'XL', 5);

-- Add migration entry
INSERT INTO migrations (name, applied_at) VALUES ('016-add-clothing-valuation-prices.sql', NOW());